FROM dotnet/interactive:latest

# Copy notebooks (So MyBinder will work)
COPY . /data/JupyterNotebooks/

# Setup volume (So you can run locally with mounted filesystem)
VOLUME /data/JupyterNotebooks/

# Set root to notebooks
WORKDIR /data/JupyterNotebooks/